services:
  app:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes: 
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./vendor:/var/www/vendor
      - ./.env:/var/www/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  myPhpAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: {}